batch_size: 16
model_name: louaaron/sedd-small
sampling_len: 32
learning_rate: 1e-5
learning_rate_Z: 1e-3
temperature: 1.0
grad_accumulation: 8
num_steps: 1500
eps: 1e-5
detach_freq: 0
back_and_forth: False
device: "cuda"
likelihood_model: <path here>
reward_batch_size: 16
reward_type: dummy
seed: 42
seq_len: 32
wandb_mode: disabled
cutoff: 0.1
loss_type: "tb"
buffer_size: 1000
sim_tolerance: 0.25
prioritization: reward
backward: False
warmup_steps: 20
reward_invtemp_end: 1.2
reward_invtemp_start: 0.9
reward_temp_sched_steps: 5000
save_dir: "."
exp_name: "test"